### PR TITLE
"Pull out weapon" function.

### PR DESCRIPTION
**Pull request by nazakomu**
Before I start, I'm not **entirely** experienced with SourcePawn myself so the difficulty of attempting to make a variable for the "client weapon information" is probably **tremendously** easier to work with for you (I elaborate later).

I've already made the console variable "influx_recording_pullout" so that one can choose _arbitrarily_ to have it enabled or disabled in the configurations. The function itself is to replicate the weapon pulling out at the initiation of a replay from Nairda's timer. If it is desired to be utilized in Influx's replay configuration, it does the following:

1). Removes the weapon at CreatePlaybackStart. This results in the replay bot entirely empty-handed and equipping nothing. // This working ultimately as desired and does not need further tweaking!

2). Gives the replay bot--**temporarily** a glock--at T_PlaybackStart so that it 'pulls' the weapon out.

The reason why it's using a glock at the moment is because there is a conflict at hand that would need to be assessed by you. I haven't figured out a proper method of giving the replay bot the weapon that is saved from the StartRecording function naturally because the GivePlayerItem function has the limitation of '**const char[] item**' on the second parameter which was adding a _stubbornly diminutive_ restriction for me when I made an attempt at making a variable that had the weapon slot data stored from the StartRecording function. Concurrently sifting throughout the code while trying to fathom what alternative method I should try, the only area that appears to save the client's weapon slots is located at the StartRecording function. This in essence indicates that the information of the weapons gathered there is **only** stored into the run when recording but doesn't have a variable that stores what information was retrieved in the StartRecording function from the client's weapon slots for further usability in this case.

So with that all being said, the _only_ thing you would have to undertake is assemble a variable that has all the weapon data saved for utilization in the parameters of GivePlayerItem.

### CODE REVIEW

**Comment by ghost** [comment]
I like the way it looks in videos but what's the actual point of it? Surely it's more realistic that the bot actually starts with the weapon in-hand as the player did during the run.

**Comment by nazakomu** [comment]
Well, I mean Influx **is** all about modularity and customization so it only makes sense that even the features that may come off as redundant are just for the sole purpose of making it a better timer and allowing for people who possess it to have as much customizability at their own will. Here you can see Influx is practically one of the only free timers (other than the discontinued OpenTimer, which is not to disregard that Mehis also made that) that have replay bots and is on par with some of the timers that can cost up to $100. Nairda's costs $100 while Blacky is all-out scamming folks with his $200 new timer. So if you contemplate about it for a while, you've got to realize Mehis is pretty damn generous and he'd end up having his timer utilized almost everywhere if he sufficed every aspect (including what can be considered unnecessary or pointless). Thus with this idea, this timer will blow those abhorrently expensive paid timers right out of the water! I ultimately hope Mehis is okay with being able to implement little things like this over time, especially if they appeared once in his roadmap for this timer. And if he's more concerned or worried about more important things, he should accomplish them first before getting to these minuscule features of the timer.

**Comment by ghost** [comment]
What a read, I wasn't debating the addition of this just asking it's purpose.

**Comment by nazakomu** [comment]
The purpose is to feature more **customization**, simple as that. I elucidated you with everything about it with my previous comment, but I am in no way trying to come off as if this were a debate or some type of harsh negotiation over whether the feature should be implemented or not.

**Comment by ghost** [comment]
Mhmm again I understand why it should be added but I'm still wondering what the actual purpose of the bot pulling out the gun on replay start is.

**Comment by nazakomu** [comment]
Uhhhh-huh.... I guess the only other "purpose" for this would be for aesthetics. Some people like the look of it (you like the look of it for videos), while some people may not. So just for a recap, the reason why it should be implemented is for more arbitrary customization while the purpose of it would be for visuals.  I don't think I can explain it any better than I already have..? At this point I'm starting to gain the feeling that you're just baiting me so I can continue replying but I see no need to respond any longer. So let's just wait for Mehis to evaluate it and see if he'll want merge the pull request or not!

**Pull request closed without merging**
